version: '3.2'
services:
    weatherstation:
        build:
            context: .
        container_name: weather-collector
        ports:
            - "7789:7789"
        volumes:
            - type: volume
              source: logsmount
              target: /logs
              volume:
                  nocopy: true
            - type: volume
              source: nfsmount
              target: /measurements
              volume:
                  nocopy: true
volumes:
    logsmount:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/logs
    nfsmount:
        driver_opts:
            type: nfs
            o: addr=azure19.hopto.org,nolock,soft,rw,nfsvers=4,rsize=131072,wsize=131072
            device: ":/"
