version: '3'
services:
    weatherstation:
        build:
            dockerfile: ./Dockerfile
            context: .
        container_name: weather-collector
        ports:
            - "7789:7789"
        volumes:
            - "nfsmount:/measurements"
volumes:
    nfsmount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=40.68.169.51
            device: ":/nfsshare/"
