version: '3'
services:
    app:
        build:
            context: .
        ports:
          - "5000:5000"
        volumes:
            - "./measurements:/database/measurements"
        environment:
            - MEASUREMENTS_DB=/database/measurements
    nfs:
        image: erichough/nfs-server:2.2.1
        privileged: true
        environment:
            - NFS_EXPORT_0=/nfsshare weather19.hopto.org(fsid=0,rw,no_root_squash)
        ports:
            - "111:111"
            - "111:111/udp"
            - "2049:2049"
            - "2049:2049/udp"
            - "32765:32765"
            - "32765:32765/udp"
            - "32767:32767"
            - "32767:32767/udp"
        volumes:
            - "./measurements:/nfsshare"